"""empty message

Revision ID: 7daf268b0b0b
Revises: 36e8a4a02788
Create Date: 2026-01-22 20:01:59.380756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daf268b0b0b'
down_revision = '36e8a4a02788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('todos', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))

    # 1. nullable=True
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # 2. rellenar datos
    op.execute("UPDATE todos SET completed = FALSE where COMPLETED IS NULL;")

    # 3. cambiar a NOT NULL 
    op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
